services:
  db:
    image: mysql:9.4.0
    container_name: jobpostings-mysql
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=jobpostings
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql

  redis-cache:
    image: redis:8.2-alpine
    container_name: redis-cache
    restart: on-failure
    environment:
      - REDIS_CACHE_PWD=${REDIS_CACHE_PWD}
    ports:
      - "6369:6379"
    volumes:
      - redis_cache_data:/data
    command: redis-server --requirepass ${REDIS_CACHE_PWD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  redis-queue:
    image: redis:8.2-alpine
    container_name: redis-queue
    restart: on-failure
    environment:
      - REDIS_QUEUE_PWD=${REDIS_QUEUE_PWD}
    ports:
      - "6359:6379"
    volumes:
      - redis_queue_data:/data
    command: redis-server --requirepass ${REDIS_QUEUE_PWD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  redis-rate-limiter:
    image: redis:8.2-alpine
    container_name: redis-rate-limiter
    restart: on-failure
    environment:
      - REDIS_RATE_LIMITER_PWD=${REDIS_RATE_LIMITER_PWD}
    ports:
      - "6389:6379"
    volumes:
      - redis_rate_limiter_data:/data
    command: redis-server --requirepass ${REDIS_RATE_LIMITER_PWD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  typesense:
    image: typesense/typesense:30.0.rc26
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors'

volumes:
  typesense-data:
  mysql-data:
  redis_cache_data:
    driver: local
  redis_queue_data:
    driver: local
  redis_rate_limiter_data:
    driver: local